# Generated by Django 4.2 on 2023-04-28 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likes',
            options={'verbose_name': 'Like', 'verbose_name_plural': 'Likes'},
        ),
    ]
