# Generated by Django 4.2 on 2023-04-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default='default-avatar-photo.jpg', null=True, upload_to='profile_pictures', verbose_name='Picture'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_info',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
    ]
