# Generated by Django 4.2 on 2023-04-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_likes_options'),
        ('authy', '0002_alter_profile_picture_alter_profile_profile_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(to='post.post'),
        ),
    ]
